name: Pipeline Feedback

on:
  push:
    branches:
    - main

jobs:
  pipeline-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout pipeline feedback
      uses: actions/checkout@v3
      with:
        repository: leondaniel22/2023-amse-template
        path: project

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Run exercise feedback
    - name: Pipeline feedback
      run: |
        ./project/test.sh